### ISSUE TITLE
Please update to version 1.25.4

### ISSUE THREAD

**Issue by eduarddejong** [muhammadsammy/free-omnisharp-vscode#44]
OmniSharp's version is now at 1.25.2. Even though they officially mark it as a pre-release (which I consider weird and confusing), it is really the current version which you are getting from Microsoft's Marketplace.

The reason I am doing this request is also because I have noticed that multiple of Roslyn's autosuggestions and completions don't work with your version 1.25.0 anymore. This seems to include both .NET 6 and .NET 7 projects.

Maybe I would need to downgrade my entire installed .NET Host / SDK version in order to get it things working for .NET 6 again. But the thing is that I have both .NET 6 and .NET 7 projects around, so that's not really a solution.

But VS Code also gets updates so it may also be related to VS Code instead. I really don't know.

(Thanks a lot for your work!)

**Comment by Dryadxon** [comment]
As a workaround you can try to set `"omnisharp.path": "1.39.2"` in the `settings.json` file of VSCodium. It should let you use .NET 7 just fine until someone have the time to help updating the extension.
Source: Works on my machine :tm:, your mileage may vary.

**Comment by pm4rcin** [comment]
I'd wait because from looking at the bug tracker of upstream there are things like crashes or .NET SDK is not detected at all etc. I think they have a good reason to not mark it as stable.

**Comment by eduarddejong** [comment]
> As a workaround you can try to set `"omnisharp.path": "1.39.2"` in the `settings.json` file of VSCodium. It should let you use .NET 7 just fine until someone have the time to help updating the extension. Source: Works on my machine tm, your mileage may vary.

Thanks! Definitely works for me as well! At least it looks like it solves the issues that I was noticing (like automatic `using` suggestions for types from new namespaces).

I didn't fully know about that option, but it's there and also with clear description.
It downloaded the new omnisharp version for me and I also see where it's storing it ( ~/.vscode-oss/extensions/muhammad-sammy.csharp-1.25.0/.omnisharp/ ), so that's also clear.

**Comment by pm4rcin** [comment]
@muhammadsammy looks like 1.25.4 is tagged as stable so you could update. Let's hope that platform-specific extensions will upload correctly.

**Comment by pm4rcin** [comment]
@muhammadsammy I have freshly looked at your recent commits today and I think that it's failing because it expects integrity checksum or smth like that for every netcoredbg archive. Just look at your most recent commit where you deleted the "integrity" https://github.com/muhammadsammy/free-omnisharp-vscode/commit/ed00a7dfe6a744c25348a2522756259df1ff9e5a field.
Since the debugger releases don't provide cheksums we could try just download it to local machine, calculate and add them this time to be sure it was that. But I don't know what exactly is that checksum since it has 64 chars. Then we could discuss what to do in the future (create an issue in Samsung's repo or calculate it in CI).

On a side note the web archive links could probably be deleted since they're several months old and were added temporarily but the problems were resolved since then.

**Comment by muhammadsammy** [comment]
Latest commits were merged but linux packaging still failing  https://github.com/muhammadsammy/free-omnisharp-vscode/actions/runs/5022001012/jobs/9004954116

**Comment by pm4rcin** [comment]
@muhammadsammy the error comes from [TarGZ installer](https://github.com/muhammadsammy/free-omnisharp-vscode/blob/ae129e9ae6f5212dbeb2336c4f9f8d8f0dfcbbff/src/packageManager/TarGzInstaller.ts#L25) file. It also explains why it fails on linux install stage since windows debugger is packaged as zip. Try to update that dependency to latest, remember to regenerate package-lock.json and I think then it should go. Of course you probably need to check if the code is correct since it may have changed a bit.

**Comment by muhammadsammy** [comment]
The problem was `ZipInstaller` was the one extracting the tar file not that `TarGzInstaller`: https://github.com/muhammadsammy/free-omnisharp-vscode/commit/cc2e04e74b03938e203548539062c7c78fa8dd40

**Comment by muhammadsammy** [comment]
CI works now and the extension is updated to 1.25.7 and published to openvsx. Thank you @pm4rcin!
